import { ethers } from "hardhat";
import bs58 from "bs58";

async function main() {
    const pk = "0x56289e99c94b6912bfc12adc093c9b51124f0dc54ac7a766b2bc5ccf558d8027"; // ewoq

    // Hardhat networks chainA, chainC URLs
    const urlA = "http://127.0.0.1:9654/ext/bc/27Kd7ibmo2HWSYG4gnoZ164hQQ8CuCgeunan7qpd3TfqRivKiy/rpc";
    const urlC = "http://127.0.0.1:9658/ext/bc/QPbg4eCHLkjnbw6U9PgD7vzX8EEcCD8C347osKjoLmvT13MWn/rpc";

    const providerA = new ethers.JsonRpcProvider(urlA);
    const providerC = new ethers.JsonRpcProvider(urlC);

    const walletA = new ethers.NonceManager(new ethers.Wallet(pk, providerA));
    const walletC = new ethers.NonceManager(new ethers.Wallet(pk, providerC));

    console.log("Using ewoq test account:", await walletA.getAddress());

    // 1. Deploy Mocks and YieldPlay on chainC
    console.log("\n[1] Deploying Contracts on chainC (Destination)...");

    const MockTokenFactory = await ethers.getContractFactory("MockERC20", walletC);
    const tokenC = await MockTokenFactory.deploy();
    await tokenC.waitForDeployment();
    const tokenCAddr = await tokenC.getAddress();
    console.log("  MockERC20 (chainC):", tokenCAddr);

    const MockVaultFactory = await ethers.getContractFactory("MockERC4626", walletC);
    const vaultC = await MockVaultFactory.deploy(tokenCAddr);
    await vaultC.waitForDeployment();
    const vaultCAddr = await vaultC.getAddress();
    console.log("  MockVault (chainC):", vaultCAddr);

    const YieldPlayFactory = await ethers.getContractFactory("YieldPlay", walletC);
    const yieldPlay = await YieldPlayFactory.deploy(await walletC.getAddress());
    await yieldPlay.waitForDeployment();
    const ypAddr = await yieldPlay.getAddress();
    console.log("  YieldPlay (chainC):", ypAddr);

    const ReceiverFactory = await ethers.getContractFactory("YieldPlayReceiver", walletC);
    const receiver = await ReceiverFactory.deploy(ypAddr, tokenCAddr);
    await receiver.waitForDeployment();
    const receiverAddr = await receiver.getAddress();
    console.log("  YieldPlayReceiver (chainC):", receiverAddr);

    await (await yieldPlay.setCrossChainReceiver(receiverAddr)).wait();
    await (await yieldPlay.setVault(tokenCAddr, vaultCAddr)).wait();

    // Give Receiver some Mock tokens to simulate bridged funds available on destination
    const FUND_AMOUNT = ethers.parseUnits("1000", 18);
    await (await tokenC.mint(receiverAddr, FUND_AMOUNT)).wait();

    console.log("  chainC config complete.");

    // 2. Deploy Sender on chainA
    console.log("\n[2] Deploying Contracts on chainA (Source)...");

    const tokenA = await MockTokenFactory.connect(walletA).deploy();
    await tokenA.waitForDeployment();
    const tokenAAddr = await tokenA.getAddress();
    console.log("  MockERC20 (chainA):", tokenAAddr);

    // Decode the base58 IDs generated by avalanche blockchain create
    const chainCidBytes32 = ethers.hexlify(bs58.decode("QPbg4eCHLkjnbw6U9PgD7vzX8EEcCD8C347osKjoLmvT13MWn").slice(0, 32));
    const chainAidBytes32 = ethers.hexlify(bs58.decode("27Kd7ibmo2HWSYG4gnoZ164hQQ8CuCgeunan7qpd3TfqRivKiy").slice(0, 32));

    const SenderFactory = await ethers.getContractFactory("YieldPlaySender", walletA);
    const sender = await SenderFactory.deploy(chainCidBytes32, receiverAddr, tokenAAddr);
    await sender.waitForDeployment();
    const senderAddr = await sender.getAddress();
    console.log("  YieldPlaySender (chainA):", senderAddr);

    console.log("  chainA config complete.");

    // 3. Register Sender as trusted on Receiver
    console.log("\n[3] Setting trusted sender on chainC...");
    await (await receiver.setTrustedSender(chainAidBytes32, senderAddr)).wait();

    // 4. Create Game and Round on chainC
    console.log("\n[4] Creating game on chainC...");
    const gameName = `AutoTest_${Date.now()}`;
    const gameId = ethers.solidityPackedKeccak256(["address", "string"], [await walletC.getAddress(), gameName]);
    await (await yieldPlay.createGame(gameName, 500, await walletC.getAddress())).wait();

    const now = BigInt(Math.floor(Date.now() / 1000));
    await (await yieldPlay.createRound(gameId, now + 5n, now + 3600n, 3600n, 100, tokenCAddr)).wait();
    const roundId = 0n;

    await new Promise((r) => setTimeout(r, 6000)); // wait for round start

    // 5. Test Cross-Chain Deposit
    const DEPOSIT_AMOUNT = ethers.parseUnits("10", 18);
    console.log(`\n[5] Calling crossChainDeposit() on chainA with ${ethers.formatUnits(DEPOSIT_AMOUNT, 18)} tokens...`);
    await (await tokenA.approve(senderAddr, DEPOSIT_AMOUNT)).wait();

    const tx = await sender.crossChainDeposit(gameId, roundId, DEPOSIT_AMOUNT);
    const receipt = await tx.wait();
    console.log("  TX hash:", receipt.hash);

    console.log("\n[6] Waiting for Relayer to deliver message (~15s)...");
    await new Promise((r) => setTimeout(r, 20_000));

    console.log("\n[7] Checking deposit on chainC YieldPlay...");
    const dep = await yieldPlay.getUserDeposit(gameId, roundId, await walletA.getAddress());
    console.log(`  exists: ${dep.exists}`);
    console.log(`  depositAmount: ${ethers.formatUnits(dep.depositAmount, 18)}`);

    if (!dep.exists || dep.depositAmount === 0n) {
        console.error("❌ FAIL: Deposit not credited.");
        process.exit(1);
    } else {
        console.log("✅ SUCCESS!");
    }
}

main().catch(console.error);
